#!/bin/bash

dev(){
    clj --main cljs.main --compile hello-world.core --repl
}

release(){
    clj -m cljs.main --optimizations advanced -c hello-world.core
}

compile_node(){
    clj -m cljs.main --target node  --output-to out/node-main.js -c hello-world.core
}

run_node(){
    node out/node-main.js
}

"$@"